### ISSUE TITLE
Disable until screen off

### ISSUE THREAD

**Issue by pordini** [RichyHBM/Monochromatic#12]
Using the widget 'Disable until screen off' turns colour on, but monochromatic activates again while the screen is still on. This behaviour is repeatable. 

Any info I can provide?

**Comment by RichyHBM** [comment]
Have you updated to the latest version? This was the case previously when the screen would reset every time the battery changed or time changed

**Comment by pordini** [comment]
Using version 0.6.1 from F-droid on Android 8.0.0.
Tested it again and it did indeed jump to monochrome again on clock minute change.

When using the persistent notification option 'screen' it does stay disabled until screen off.

**Comment by RichyHBM** [comment]
Ahh ok, my bad, I hadnt updated the widget with the same logic as the notification then

**Comment by RichyHBM** [comment]
Latest version, 0.6.2 should fix this

**Comment by pordini** [comment]
Just to report: all works fine now.
