### ISSUE TITLE
Separate monochromatic from blue light filter

### ISSUE THREAD

**Issue by jfmcbrayer** [RichyHBM/Monochromatic#14]
I'm using a Moto G5, so a pretty stock Android. I have monochromatic installed from F-Droid.

Enabling Monochromatic, then disabling it temporarily through any of the provided means (notification, quick tile) turns color back on, but also turns on the blue light filter. I often would like to use Monochromatic during the day, and disable it temporarily to get color, without enabling the blue light filter at the same time. Normally my blue light filter is controlled by the Moto system app, which turns it on and off at set times.

**Comment by RichyHBM** [comment]
I'm unsure what you mean? You can disable the bluelight filter in settings

**Comment by jfmcbrayer** [comment]
The problem was that with "also control blue light filter" unchecked in settings, the blue light filter came on whenever disabling monochromatic. However, this seems to have stopped (Monochromatic update? Interaction with me opening Moto system app? I don't know.), so it's probably best to just close this.

**Comment by RichyHBM** [comment]
Ok, if this continues please feel free to re-open it!
