### ISSUE TITLE
Per app setting 

### ISSUE THREAD

**Issue by pordini** [RichyHBM/Monochromatic#15]
Would be awesome if monochromatic could be automatically disabled for specific user selectable apps while they're in foreground, then reenable when that app is no longer in foreground. 

Example could be camera, gallery, stuff like that.

**Comment by RichyHBM** [comment]
I really like this idea, will investigate and hopefully add it for the next point feature

**Comment by RichyHBM** [comment]
Seem to have this working in the white list branch, I'm going to try it out on my device for a few days to make sure there aren't any obvious bugs and then update!

**Comment by RichyHBM** [comment]
Pushed the update!

**Comment by pordini** [comment]
Awesome, works great!
