### ISSUE TITLE
'Always On' interferes with grayscale toggle

### ISSUE THREAD

**Issue by mollusko** [RichyHBM/Monochromatic#22]
When 'always on' is enabled pressing the grayscale toggle in quick settings results in a moment of color followed by reversion to grayscale; there appears to be no way to toggle from grayscale without disabling 'always-on'.  Is the toggle handled by the system?  Shouldn't the toggle (temporarily) override the 'always-on' setting?

Thanks for an excellent app, it has afforded me a significantly improved use & enjoyment of my device!

**Comment by RichyHBM** [comment]
The always on was intended as a definite thing, i.e. it wouldnt get overriden.

**Comment by mollusko** [comment]
Fair enough, thanks for clarifying!
