### ISSUE TITLE
Add battery trigger

### ISSUE THREAD

**Issue by licaon-kter** [RichyHBM/Monochromatic#3]
Eg. If below X% (that we can setup) enable mono as it might help lower the battery drain on AMOLED devices.

Ref: https://github.com/theblixguy/Monochrome

**Comment by RichyHBM** [comment]
Working on it in https://github.com/RichyHBM/Monochromatic/tree/battery_level, want to test a bit more before merging in

**Comment by licaon-kter** [comment]
Set it at 66%, done stuff, rebooted, battery at 64%, app service not loaded(?!), start the app....no change....

Go to settings, toggle "battery" on/off....nothing...
 

/LE: the service should be always running, now it runs ony if Imuse the main toggle
Or how you detect battery level?

**Comment by RichyHBM** [comment]
Hmm, so it didnt load the service on boot? Thats very odd, it works on my phone though takes like a minute to load up all the boot applications

**Comment by RichyHBM** [comment]
I might make it so that when you open the app, if the toggle is set it should just automatically start the service

**Comment by licaon-kter** [comment]
Yes, on start you should check and setup stuff.

But anyway, now, at 64% set it at 62, swiped your app...byebye...now at 62 nothing happens...since...there's no service...unless I toggle the main toggle...which is not what I want.

**Comment by RichyHBM** [comment]
I have pushed a commit to address it not starting the service when previously enabled. As for the battery seting, in order to be able to customise the battery level at which it should activate it needs to run the service, otherwise I can only listen to the BatteryService Broadcast for low battery that happens (by default) at 15%

**Comment by licaon-kter** [comment]
Not helping, the service does not run, as said above, unless I toggle the main toggle (that instantly goes to mono).

I'm on AOSP Pie, if it matters.

**Comment by RichyHBM** [comment]
So, do you have time based and always-on both disabled? only battery based enabled? On my device it only triggers mono when the battery percent changes to be same or less than the setting

**Comment by licaon-kter** [comment]
Except the main "make it mono now" switch neither the time nor the battery options work.

Not sure what "always on" should do exactly.

FYI I even left the app running (not swiped).

**Comment by RichyHBM** [comment]
And the service shows right?

The main toggle on the first screen enables the service, then the options in settings let you change when you actually want the monochrome to start. It may be that android 9 has changed how it works, do https://github.com/fei-ke/Greyscale or https://github.com/theblixguy/Monochrome work correctly?

**Comment by RichyHBM** [comment]
Tried on android pie emulator and it seemed to work fine, cou.d you let me know if it works when using time based or with always on?

**Comment by licaon-kter** [comment]
Ok, more testing.

So I setup a trigger, then main toggle needs to be on, ok.

Looks like battery trigger is working, if I select a higher % than current it triggers right away.

The time based one doesn't trigger though (with or without a battery one setup at the same time)

Also, could you add a "never show again" checkbox to that Android 8 warning, it gets old pretty fast.

**Comment by RichyHBM** [comment]
If you then turn your screen off and on, do you see it go monochrome? I think it may be that you expect it to switch directly where as at the moment you need to turn the screen off for it to trigger. I'm going to see iff I can fix this now

**Comment by RichyHBM** [comment]
Fixed the issue with preferences, hopefully it should now work as you expect it!

**Comment by licaon-kter** [comment]
Looks like its working now. Thanks
