### ISSUE TITLE
Permission secure

### ISSUE THREAD

**Issue by Bebarr** [RichyHBM/Monochromatic#7]
Hi,
I have just download this app and I'm this is a good one! But I don't know how to set up the permission secure to launch the app. Please help me :) I'm not a specialist. And I'm french, my "english tech language" is limited..
Thanks !! :)

**Comment by RichyHBM** [comment]
Hello, easiest way to explain is first set up ADB on your computer with https://wiki.lineageos.org/adb_fastboot_guide.html
Then on your phone go into settings -> about and tap the version number 7 times to enable developer mode.

From there you should just plug the USB in and should get a message on your phone, accept it and paste the command into your pc

**Comment by Bebarr** [comment]
Ok, thanks. But i don't succeed to install ADB on my computer. :/

**Comment by madeindjs** [comment]
Is there any way to do this without ADB? I mean only with Android device?

**Comment by RichyHBM** [comment]
@madeindjs Unfortunatelly not, at least not without root which I dont really want to add. If you dont want to install a full android sdk, I think you can install just the minimum ADB requirements
